import logoSenaVerde from "/logoSenaNaranja.png";
import logoTic from "/def_LOGOTIC.png"

import {
  HomeIcon,
  MapIcon,
  DocumentTextIcon,
  ServerIcon,
  ClockIcon,
  MagnifyingGlassIcon,
  ChevronRightIcon,
  BuildingOfficeIcon,
  UserIcon,
  EnvelopeIcon,
  UserCircleIcon,
  TruckIcon,
  PlusIcon,
  TrashIcon,
  UsersIcon,
  UserGroupIcon,
  UserMinusIcon,
  ShieldCheckIcon,
  EllipsisHorizontalCircleIcon,
  PencilIcon,
  GlobeAltIcon,
  BuildingLibraryIcon,
  WrenchIcon,
  DocumentIcon,
  PencilSquareIcon,
  ComputerDesktopIcon,
  NewspaperIcon
} from "@heroicons/react/24/outline";

export const V = {
  logoSena: logoSenaVerde,

  bg_sena_verde: "bg-green-600",
  text_white: "text-white",

  radius: "rounded-lg",

  HomeIcon,
  MapIcon,
  DocumentTextIcon,
  ServerIcon,
  ClockIcon,
  UserIcon,
  EnvelopeIcon,
  UserCircleIcon,
  TruckIcon,
  PlusIcon,
  TrashIcon,
  UsersIcon,
  UserGroupIcon,
  MagnifyingGlassIcon,
  ShieldCheckIcon,
  UserMinusIcon,
  ChevronRightIcon,
  EllipsisHorizontalCircleIcon,
  PencilIcon,
  logoTic,
  GlobeAltIcon,
  BuildingOfficeIcon,
  BuildingLibraryIcon,
  WrenchIcon,
  DocumentIcon,
  PencilSquareIcon,
  ComputerDesktopIcon,
  NewspaperIcon,
  Bradius: "sm",

  btnPrimary: "primary",
  btnSecundary: "bg-green-600",
};
